{
 "title": "Flare Network Alerts",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Ftso Reward Manager Tx Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ftso_reward_manager_transaction_count"
    }
   ]
  },
  {
   "title": "Inflation Tx Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "inflation_transaction_count" }
   ]
  },
  {
   "title": "Flare Daemon Tx Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "flare_daemon_transaction_count" }
   ]
  },
  {
   "title": "Ftso Reward Manager Balance Check",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(ftso_reward_manager_current_balance_nat / ftso_reward_manager_total_unclaimed_awards_outstanding_nat) * 100"
    }
   ]
  },
  {
   "title": "Annual Inflation Recognized",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "time() - inflation_current_annum_end_time_stamp"
    },
    {
     "expr": "inflation_reward_epoch_start_ts"
    }
   ]
  },
  {
   "title": "Daily Inflation Authorized",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "block_number_ts - inflation_last_authorization_ts"
    },
    {
     "expr": "inflation_reward_epoch_start_ts"
    }
   ]
  },
  {
   "title": "Flare Daemon Total Daemonized Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "flare_daemon_total_daemonized_errors"
    }
   ]
  },
  {
   "title": "Flare Daemon Block Holdoffs Remaining",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "flare_daemon_block_holdoffs_remaining"
    }
   ]
  },
  {
   "title": "Flare Daemon Minting Outstanding Nat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "flare_daemon_minting_outstanding_nat"
    }
   ]
  },
  {
   "title": "Flare Daemon Trigger Block Delta",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "block_number - flare_daemon_system_last_triggered_at"
    }
   ]
  }
 ]
}