erDiagram
          Ledger ||--o{ Account : "composed of"
          Ledger {
            uint256 assetBalance
            uint256 liabilityBalance
            uint256 equityBalance
          }
          FlareNetworkGeneralLedger ||--|| Ledger : "is a"
          FlareNetworkGeneralLedger ||..|| FlareNetworkChartOfAccounts : "defined by"
          FlareNetworkChartOfAccounts ||--o{ AccountDefinition : "composed of"
          AccountDefinition {
            string name
            enum accountType
          }
          Account ||--o{ LedgerEntry : "has"
          Account {
            string name
            enum accountType
            uint256 currentBalance
          }
          LedgerEntry {
            uint256 blockNumber
            uint256 credit
            uint256 debit
            uint256 runningBalance
          }
          MintAccounting ||..|| FlareNetworkGeneralLedger : "posts to and queries"
          MintAccounting ||..|| FlareNetworkChartOfAccounts : references
          SupplyAccounting ||..|| FlareNetworkGeneralLedger : queries
          SupplyAccounting ||..|| FlareNetworkChartOfAccounts : references
          FtsoInflationAccounting ||..|| FlareNetworkGeneralLedger : "posts and queries"
          FtsoInflationAccounting ||..|| FlareNetworkChartOfAccounts : references
          FtsoRewardManagerAccounting ||..|| FlareNetworkGeneralLedger : "posts and queries"
          FtsoRewardManagerAccounting ||..|| FlareNetworkChartOfAccounts : references
          FlareKeeper ||..|| MintAccounting : "receives minting requests; posts minting received"
          FlareKeeper ||..|| FtsoRewardManager : funds
          FtsoRewardManager ||..|| FtsoRewardManagerAccounting : "posts earned, claimed and expired rewards; receives supply"
          FtsoRewardManager ||..|| SupplyAccounting : "gets distributable balance"
          MintingFaucet ||..|| FlareKeeper : "proxies FLR transfers"
          MintingFaucet ||..|| IWithdrawAmountProvider : "gets withdraw amount from"
          FtsoRewardManagerTopup ||--|| IWithdrawAmountProvider : "is a"
          FtsoRewardMintingFaucet ||--|| MintingFaucet : "is a"
          FtsoRewardMintingFaucet ||..|| FtsoInflationAccounting : "posts ftso minting withdrawls"
          FtsoRewardMintingFaucet ||..|| FtsoRewardManagerTopup : "has a"
          InflationAuthorizer ||..|| SupplyAccounting : "gets inflatable balance"
          InflationAuthorizer ||..|| IInflationPercentageProvider : "gets inflation percentage"
          FtsoInflationPercentageProvider ||--|| IInflationPercentageProvider : "is a"
          FtsoInflationPercentageProvider ||..|| Constitution : "get ftso inflation percent"
          FtsoInflationAuthorizer ||--|| InflationAuthorizer : "is a"
          FtsoInflationAuthorizer ||..|| FtsoInflationAccounting : "authorizes minting"
          MintingFaucet ||..|| MintAccounting : "makes minting requests"
          FtsoInflationAuthorizer ||..|| FtsoInflationPercentageProvider : "has a"
          