sequenceDiagram
    autonumber
    participant Validator
    participant FlareKeeper
    participant FtsoMintingFaucet
    participant FtsoRewardManagerTopup
    participant MintAccounting
    loop Every block
        Validator-->FlareKeeper: trigger()
        activate FlareKeeper
        FlareKeeper-->FtsoMintingFaucet: keep()
        alt mint every (fundWithdrawTimeLockSec - fundRequestIntervalSec)
            FtsoMintingFaucet->FtsoRewardManagerTopup: getAmountTWei()
            FtsoMintingFaucet->MintAccounting: requestMinting(amount)
            FlareKeeper->MintAccounting: getMintingRequested()
            FlareKeeper->Validator: mint request
            Validator->FlareKeeper: conjure FLR
        else next block after mint
            FlareKeeper->MintAccounting: receiveMinting(amount)
        end
        deactivate FlareKeeper        
    end    