sequenceDiagram
    autonumber
    participant Validator
    participant FlareKeeper
    participant FtsoMintingFaucet
    participant FtsoInflationAccounting
    participant FtsoRewardManager
    participant FtsoRewardManagerAccounting
    loop Every block
        Validator-->FlareKeeper: trigger()
        activate FlareKeeper
        FlareKeeper-->FtsoMintingFaucet: keep()
        alt withdraw every fundWithdrawTimeLockSec
            FtsoMintingFaucet->FtsoMintingFaucet: withdrawRewardFundsCallback(amount)
            FtsoMintingFaucet->FtsoInflationAccounting: receiveMinting(amount)
            FtsoMintingFaucet->FlareKeeper: transferTo(rewardManager, amount)
            FlareKeeper->FtsoRewardManager: transfer(amount)
            FtsoRewardManager->FtsoRewardManagerAccounting: receiveSupply(amount)
        end
        deactivate FlareKeeper        
    end    